### ISSUE TITLE
ctgov_query did not seem to work as expected

### ISSUE THREAD

**Issue by xiaolongluo1979** [presagia-analytics/ctrialsgov#18]
Hi, I ran the following 

studies_nsaa<-ctgov_query(outcome_kw=c("NSAA","North Star","North Star ambulatory assessment"), match_all = FALSE)

and expected the result studies_nsaa should include all trials with outcome measure including "North Star". However, it did not include NCT00468832, which does include North Star ambulatory assessment in outcome. Any advice?

BTW, which is the difference between outcome_kw and outcome_desc_kw ?

Thanks,
Xiaolong

**Comment by k-maciejewski** [comment]
It appears that the derived dataset may be out of date. The latest "last_update" in the derived data is October 31, 2022. I compared to the download from AACT and NCT numbers are "missing" from the package's derived dataset.

**Comment by statsmaths** [comment]
Sorry, I somehow missed this old comment. Perhaps you were not using the full database and only querying the sample version?

It also looks like you are using the CRAN version, which has some different options. We recommend using the version on GitHub as it's more up-to-date with the current ClinicalTrials.gov website.
