### ISSUE TITLE
filter_keywords() doesn't work for nested data.frame

### ISSUE THREAD

**Issue by kaneplusplus** [presagia-analytics/ctrialsgov#5]
The filter_keywords() function does not work for nested data.frames. Is there a preferred way to filter trials based on interventions?

I added a function has_term() that can be used like the following:

``` r
studies %>% filter(map_lgl(interventions, ~ has_term(.x$name, "Pembrolizumab"))
```

for example to keep the trials where pembro appears as one of the interventions. Is there a better way to do this?

**Comment by statsmaths** [comment]
Good point, though I am not sure what you are referring to by the `filter_keywords` function. I think the method you have for searching the nested data frame is fine. Perhaps we could just wrap it inside `ctgov_query` as one of the query methods?
