### ISSUE TITLE
Calculate values for `ol` object: `sponsor_type` designations have changed

### ISSUE THREAD

**Issue by kaneplusplus** [presagia-analytics/ctrialsgov#7]
It looks like the sponsor types have changed in the latest database dump:

```{r}
> names(table(ctrialsgov:::.volatiles$tbl_join$sponsor_type))
 [1] "AMBIG"     "FED"       "INDIV"     "INDUSTRY"  "NETWORK"   "NIH"
 [7] "Other"     "OTHER"     "OTHER_GOV" "UNKNOWN"
```
Can `ol` be added to the volatiles and be calculated when `ctgov_create_data(con)` is called?

**Comment by kaneplusplus** [comment]
As an alternative,`sponsor_type` could be included in the arguments handled by `ignore_case`.

**Comment by statsmaths** [comment]
Most recent commit now creates the `ol` list when creating the data and stores it in `.volatiles`. We can talk about the ignore case option tomorrow in case that still makes sense too.
