### ISSUE TITLE
The size of the static dataset

### ISSUE THREAD

**Issue by OleksiyAnokhin** [presagia-analytics/ctrialsgov#8]
Hi team, kudos for your excellent work!  A quick question. How big is the database? Is it the full data from Clinical Trials or you cut it?

`Alternatively, we can download a static version of the data from GitHub and load this into R without needing the setup a local version of the database.`

`**The static dataset is updated monthly**.`

**Comment by kaneplusplus** [comment]
The data set is not big. I think our rough estimate was that, when held as a dataframe it would be of the order 2 GB.
